export const courseData = [
  {
    level: "Beginner",
    title: "English punctutation made easy",
    img: "/course1.jpg",
    stars: 3.6,
    enrolled: 120,
    author: "Jake McAddams",
    price: 499,
    content: ["Basic Grammer", "How to talk about your work", "Tenses"],
  },
  {
    level: "Advance",
    title: "Mastering English verbs",
    img: "/course2.jpg",
    stars: 4.6,
    enrolled: 80,
    author: "Charlie Jones",
    price: 899,
    content: ["Advance Grammer", "Script Writing", "Business English"],
  },
  {
    level: "Intermediate",
    title: "French for you",
    img: "/course3.jpg",
    stars: 3.8,
    enrolled: 600,
    author: "Elyna Monet",
    price: 599,
    content: ["Writing Emails", "French cuisine"],
  },
  {
    level: "Intermediate",
    title: "Spanish 100",
    img: "/course4.jpg",
    stars: 4.0,
    enrolled: 200,
    author: "Diego Martínez",
    price: 599,
    content: [
      "Introduce Yourself in Spanish",
      "Counting numbers and verbs",
      "Spanish culture",
    ],
  },
];
