export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Signup } from "./Signup";
export { default as Quiz } from "./Quiz";
export { default as Result } from "./Result";
export { default as Contact } from "./Contactus";
export { default as Meeting } from "./Meeting";
export { default as Courses } from "./Courses";
export { default as SingleCourse } from "./SingleCourse";
export { default as QuizList } from "./QuizList";
export { default as NewQuiz } from "./NewQuiz";
export { QuizMaker } from "./QuizMaker";
