export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Signup } from "./Signup";
export { default as Quiz } from "./Quiz";
export { default as Result } from "./Result";
export { default as Contact } from "./Contactus";
export { default as Meeting } from "./Meeting";
export { default as Courses } from "./Courses";
export { default as Sessions } from "./Sessions";
export { default as SingleCourse } from "./SingleCourse";
export { default as QuizList } from "./QuizList";
export { default as NewQuiz } from "./NewQuiz";
export { QuizMaker } from "./QuizMaker";
export { default as Dashboard } from "./Dashboard";
export { default as Qna } from "./Qna";
export { default as SingleQna } from "./SingleQna";
export { default as PageNotFound } from "./PageNotFound";
export { CourseSection } from "./CourseSection";
export { CreateCourse } from "./CreateCourse";
export { default as MyCourse } from "./MyCourse";
export { default as Loading } from "./Loading";
export { default as TeacherDashboard } from "./TeacherDashboard";
export { default as Profile } from "./Profile";
